#!/usr/bin/python3

import os
import sys

try:
   if sys.argv[1] == "start":
      os.system("scutum --enable")
      exit(0)
   elif sys.argv[1] == "stop":
      os.system("scutum --disable")
      exit(0)
   elif sys.argv[1] == "restart":
      os.system("scutum --reset")
      os.system("scutum")
      exit(0)
   else:
      print("Usage: scutum {start|stop|status|restart}")
      exit(0)
except Exception as e:
   print("Usage: scutum {start|stop|status|restart}")