#!/usr/bin/env python3
### BEGIN INIT INFO
# Provides:          scutum
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-­Start:    
# Required­-Stop:     
# Should­-Start:      
# Should-­Stop:       
# X-Interactive:     true
# Short-Description: SCUTUM Firewall
# Description:       Start SCUTUM firewall
#  This script will start SCUTUM Firewall.
### END INIT INFO

import os
import sys

try:
   if sys.argv[1] == "start":
      os.system("scutum --enable")
      exit(0)
   elif sys.argv[1] == "stop":
      os.system("scutum --disable")
      exit(0)
   elif sys.argv[1] == "restart":
      os.system("scutum --reset")
      os.system("scutum")
      exit(0)
   else:
      print("Usage: scutum {start|stop|status|restart}")
      exit(0)
except Exception as e:
   print("Usage: scutum {start|stop|status|restart}")